### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by hsavit1** [dparnell/rethink-db-client#2]
Hey, 

I was trying to follow your cloning instructions and I'm getting stuck on the last step

on the 'git submodule update' step im getting the following error

Cloning into 'RethinkDbClient/Protocol/protobuf-objc'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:dparnell/protobuf-objc.git' into submodule path 'RethinkDbClient/Protocol/protobuf-objc' failed

**Comment by dparnell** [comment]
Hi, I just changed the reference to the protobuf-objc repo to the https style.  Pull that down and see if that makes a difference.

**Comment by hsavit1** [comment]
works great thanks!
