### ISSUE TITLE
No longer compatible with RethinkDB 2.3

### ISSUE THREAD

**Issue by ekscrypto** [dparnell/rethink-db-client#3]
Error Domain=RethinkDB Error Code=-1004 "ERROR: The PROTOBUF client protocol is no longer supported
" UserInfo={NSLocalizedDescription=ERROR: The PROTOBUF client protocol is no longer supported
}

**Comment by dparnell** [comment]
Hi,
  fixing this requires the driver to be reworked significantly. I'm no longer using this driver myself, but it is something I do want to do eventually. If I get some time to work on it I'll see what I can do. As to when that will be I couldn't say.

Sorry I can't be more helpful
Daniel

**Comment by dparnell** [comment]
I've started building JSON mode support on the json branch

**Comment by dparnell** [comment]
I've merged in a first cut of the new JSON based network transport, so you should be able to use this code with the latest version of RethinkDB
